### ISSUE TITLE
Moving from Dexie 3.2.5 to 4.0.1 creates webpack failure

### ISSUE THREAD

**Issue by lesjames** [dexie/Dexie.js#1955]
In an existing project I'm currently using Dexie 3.2.5. I bumped the version to 4.0.1 in package.json. After npm install and running a serve with webpack I get the following error.

```
Error: File './src/tsconfig.json' not found.
    at Be (/node_modules/get-tsconfig/dist/index.cjs:3:9201)
    at ie (/node_modules/get-tsconfig/dist/index.cjs:3:10245)
    at le (/node_modules/get-tsconfig/dist/index.cjs:3:10975)
    at Object.Le [as getTsconfig] (/node_modules/get-tsconfig/dist/index.cjs:3:11080)
    at Object.ESBuildLoader (/node_modules/esbuild-loader/dist/index.cjs:65:36)
    at LOADER_EXECUTION (/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at /node_modules/webpack/lib/NormalModule.js:920:15
```

I do not use Typescript in my project. If I go into /node_modules/dexie/ and remove tsconfig.json then I'm able to build and serve the project.

**Comment by lucaju** [comment]
Similar error (and I do use Typescript.)

It seems that the source of the error is on `tsconfig.json` on Dexie. It extends the config from a file that is not shipped with the library:
```
{
  "extends": "./src/tsconfig.json",
}

```

**Comment by dfahlander** [comment]
Thanks! I've seen it and it was resolved in https://github.com/dexie/Dexie.js/commit/7131ade3cfe0fc6d21a3645c5fc5fe86122c1813. A new version out soon.

**Comment by lucaju** [comment]
The error persists on v.4.0.2
`Error: File './src/tsconfig.json' not found.`

tsconfig.json still ships with the package and still makes reference to a file not on the package
```
{
  "extends": "./src/tsconfig.json",
}
```
