### ISSUE TITLE
Once Dexie.on.close is triggered, Dexie.isOpen() is still true.

### ISSUE THREAD

**Issue by twxia** [dexie/Dexie.js#2186]
https://dexie.org/docs/Dexie/Dexie.on.close

Is it normal that when the close event is triggered, the connection is still open?  

Currently, I need to call `db.close()` by myself in the close event and `db.open()` again to trigger the ready event that a middleware depends on it. 

I guess we need to subscribe to close event in [constructor](https://github.com/dexie/Dexie.js/blob/master/src/classes/dexie/dexie.ts#L96) and `this.close()` to prevent this issue. I can create a PR if needed.

**Comment by dfahlander** [comment]
No that would be considered a bug. There has been a change in this aspect in 4.2.0 compared to 4.0.11. Chances are the issue is solved in 4.2.0. Could you try to create a repro in [jsfiddle](https://jsfiddle.net/3tf5r0cu/) or similar and try it on both 4.0.11 and 4.2.0?

**Comment by twxia** [comment]
Hi @dfahlander, thanks for the quick response. The issue is still existing in 4.2.0. 

Please check it here: https://jsfiddle.net/2548cqf0/. 
Trigger close event by clearing the history via chrome://settings/clearBrowserData.

For the `Dexie.delete()`, I can only get the updated connection states and related logics in another event loop, https://jsfiddle.net/1oxv8Lrm/. I'm not sure if it is expected.

BTW, if you have time, could you check this as well https://github.com/dfahlander/dexie-encrypted/pull/1 ? 🙏

**Comment by dfahlander** [comment]
I've merged a fix that makes dexie reset its states equivalently no matter if db.close() is called, or if database was closed from outside. This is released on npm as dexie@4.2.1-rc.1 (or currently dexie@test). Running your repro makes the first call still return isOpen true (due to that the callback is called just before the state reset happens) but the next output is isOpen: false.

CI tests pass etc but I'll be waiting with releasing it as stable for some time. Please try it and report if any issues comes out of this subtle change.

*Regarding dexie-encrypted, please try dexie-encrypted@next released today. Only deps are updated in it*

**Comment by dfahlander** [comment]
Closing as it's fixed in dexie@4.2.1-rc.1.
